### ISSUE TITLE
Crash during modloading

### ISSUE THREAD

**Issue by Mythrrinthael** [ThexXTURBOXx/Reforged-Integration#3]
I recently downloaded both Reforged and Reforged: Integration. The latter crashes the client during modloading.

[This](http://pastebin.com/NutzBpRy) is what seems to be the relevant part of the error report. Note that it points at Thaumcraft assets while the mod load list mentions the Project E part of the mod had an error. I have the latter installed, but not the former; according to Reforged: Integration's infopage it should have been possible to use it nevertheless.

**Comment by ThexXTURBOXx** [comment]
Ok, I know the problem... I used Eclipse's built-in "Clean-up"-method and it seems that it changed the Aspect-part to a public static final Aspect. If I just remove the "final" it should run again. I will try that.

**Comment by ThexXTURBOXx** [comment]
Tested it, fixed the crash. So this will be fixed in the new update!
