### ISSUE TITLE
Crash during modloading part 2 (Electric Boogaloo)

### ISSUE THREAD

**Issue by Mythrrinthael** [ThexXTURBOXx/Reforged-Integration#4]
I recently downloaded version 0.2.2 of the mod, which includes the fix to the modloading crash when Thaumcraft isn't present. Unfortunately, it still crashes. [Relevant data from log](http://pastebin.com/isQyUmXZ).

**Comment by ThexXTURBOXx** [comment]
Are you sure, that you have the latest version of my mod? At my client it works (even when no mod can get integrated) o_O
Well, then I try the last thing I can do.

**Comment by ThexXTURBOXx** [comment]
Should got fixed in release 0.2.3-alpha with the commits d69db7d746b9d0f08084db417006a8dc9591c47b and 422ce18c2285a175afe008408a088e29dd142012.
