### ISSUE TITLE
(Solved; old compatibility settings in config) Crash during modloading part 3: NullPointerException

### ISSUE THREAD

**Issue by Mythrrinthael** [ThexXTURBOXx/Reforged-Integration#5]
I'm back with yet another issue. Minecraft produces a NullPointerException while handling the Thaumcraft bit of your mod. [Here](http://pastebin.com/v8Ap0bX0)'s the relevant bits from the log - excluding the list that shows the Thaumcraft part of your mod errored during pre-init.

This time, I have Thaumcraft installed but not ProjectE, though (the lack of) ProjectE doesn't seem to be the cause here.

**Comment by ThexXTURBOXx** [comment]
I have no idea, what could be the issue there... For me it works perfectly though o_O 
But it doesn't even look like an error of my mod (seems like the API of Thaumcraft would be broken a little bit).

**Comment by Mythrrinthael** [comment]
Well, everything (including Thaumcraft and regular Reforged) works fine if I remove Integration. Where else could the problem lie?

**Comment by TheOnlySilverClaw** [comment]
I have a suspicion, but cannot test it without having a reforged-integration workplace set up.
The fact that the error only occurs in the musket+knife recipe (line 93) and the NullPointerException might mean that there is a problem with setting the values for knife or musket before.
Better check what their values are before line 93.
But maybe make sure you are using the same code first.

**Comment by ThexXTURBOXx** [comment]
I really can't reproduce the error and have no idea what is the problem, I will look at this again, when I am finished with the crossbow.

**Comment by ThexXTURBOXx** [comment]
Could you please send me the whole log and the crash report (please separately out from the crash-reports-folder)? That could help me further.
P.S.: Which version of Reforged, which version of Reforged Integration, which version of Thaumcraft and which version of Forge is installed? You need at least Reforged 0.7-pre1 to run the Reforged Integration 0.2-builds...

**Comment by Mythrrinthael** [comment]
> Could you please send me the whole log and the crash report (please separately out from the crash-reports-folder)? That could help me further.
> P.S.: Which version of Reforged, which version of Reforged Integration, which version of Thaumcraft and which version of Forge is installed? You need at least Reforged 0.7-pre1 to run the Reforged Integration 0.2-builds...

I'm not sure which log you're after (and where I could find it), but [here](http://pastebin.com/nkqGndKD)'s a pastebin with the full crash report.

I did double-check which Reforged version I was using and it was indeed 0.7-pre1. You'll be able to see it in the crash log I pastebinned as well.

**Comment by ThexXTURBOXx** [comment]
in your minecraft-folder, there should be a directory, called "logs". There is a file fml-client-latest.log. I need that file (if you ran minecraft with our mod)

**Comment by Mythrrinthael** [comment]
> in your minecraft-folder, there should be a directory, called "logs". There is a file fml-client-latest.log. I need that file (if you ran minecraft with our mod)

There's no log file regarding this error. I'm assuming this is because the crash happens during the pre-initialization phase, whereas these logs only show events after a world is loaded.

**Comment by ThexXTURBOXx** [comment]
At my client, it generates logs since the launcher closes... This is crazy o_O

**Comment by ThexXTURBOXx** [comment]
Wait, did you disable the musket in the config? If you did so, I know the problem (and I know how to fix it... I will even fix it, if you didn't disable it XD ). For my client it still works:
!["Proof"](https://cloud.githubusercontent.com/assets/12763829/14229805/94fa7bee-f93e-11e5-8446-b86fce07d2d1.jpg)

**Comment by Mythrrinthael** [comment]
The musket was not disabled.

However, I think I found the exact place of the issue: an **old** config file of Reforged Integration that had the compatibility settings _reversed_ compared to my mod loadout: Thaumcraft = false, ProjectE = true, while I didn't have Project E and did use Thaumcraft. Correcting that (Thaumcraft = true, Project E = false) solved the issue.

Is it possible to let Reforged Integration check which of the two mods are available and load content based on that?

**Comment by ThexXTURBOXx** [comment]
I have already tried this, but I had the problem, that you can't change the config then yourself (as a modpack creator you may have to do this for balancing). Maybe I find a better way for this later on...

**Comment by ThexXTURBOXx** [comment]
Ok, I will just remove the config in the next update... I will try to find a better way anytime later on...

**Comment by ThexXTURBOXx** [comment]
I will release the new version in a few minutes
