### ISSUE TITLE
Thaumcraft issue

### ISSUE THREAD

**Issue by Liiw** [ThexXTURBOXx/Reforged-Integration#6]
Hello. I tried to install Reforged-Integration along with Thaumcraft, and it seems to have a problem:

[crash-2016-06-12_21.54.02-client.txt](https://github.com/ThexXTURBOXx/Reforged-Integration/files/310923/crash-2016-06-12_21.54.02-client.txt)

**Comment by ThexXTURBOXx** [comment]
You need the Version 0.7-pre1 of Reforged (You used 0.6.1). Since Reforged Integration 0.2, this is the minimum needed Version.

**Comment by ThexXTURBOXx** [comment]
P.S.: I don't recommend using the 0.7-pre2, because it is VERY buggy...

**Comment by Liiw** [comment]
This was indeed the issue. Thank you for your assistance.

**Comment by ThexXTURBOXx** [comment]
No problem ^^
